### ISSUE TITLE
Ideas?

### ISSUE THREAD

**Issue by remotevase** [BoxOfDevs/Archived#1]
Want to start a new project? Propose the idea here!

**Comment by lavender-sys** [comment]
PocketMine-CSS
Helpful stuff for starting a MCPE-related website.
https://github.com/Dog2puppy/PocketMine-CSS I've kinda already started but I'm failing, so I wanted it to be moved to BoxOfDevs because I know a lot of people here have good css skills.

**Comment by remotevase** [comment]
@Dog2puppy My css skills are moderate at best, but okay! Lets get other team feedback!

**Comment by Vaults1** [comment]
Maybe we should have a proposal repo where _**anyone**_ can commit their repo to it, so it can be considered for transfer to BOD.

**Comment by remotevase** [comment]
Maybe?

**Comment by HimbeersaftLP** [comment]
What about the two ideas I wrote in the IM convo?

**Comment by remotevase** [comment]
I forgotten them... Please repost here

**Comment by HimbeersaftLP** [comment]
New plugin ideas:
Build Vote
Players can make their build voteable by creating a sign
Vote for other people's builds by clicking on the player's sign
API Bumper
Automatically bumps the API of a plugin
Uses DevTools to pack and unpack

**Comment by remotevase** [comment]
Another idea: BoxofBits V2. Similar to a core for a server, it will have multiple plugins put into one
1. SurvivalGames by ImagicalGamer
2. HungerGames by xBeastModex
3. AntiCheat by DarkWav
4. Economy by onebone
5. HomeTP by me
6. /Spawn by IDK
7. PerWorldGM or WorldGM (one of the 2, IDK because one of them works the other doesn't)
8. ChatFilter by EpicSteve33
9. AFK Kicker
10. Command Blocks by Ad5001
11. Build Vote game
12. Most of the features in BoxofBits Original
13. IDK, but there's a lot more too.

@BoxOfDevs/plugin-devs what do you think? It will be AWESOME if we do it, but it will be super hard

**Comment by HimbeersaftLP** [comment]
Like hype-spooning? :P

**Comment by dragonwocky** [comment]
That would be called BoxCore - BoxOfBits will remain what it was originally going to be! (one day I'll start working on it again :P)

**Comment by remotevase** [comment]
@TheDragonRing Good idea! BoxCore. I'll start tmro

**Comment by dragonwocky** [comment]
Eventually (once I get BoxOfBits started again) maybe we could modify BoxCore and BoxOfBits to be partner plugins, so BoxCore (if this happens, then maybe call it BoxMinigames) just has the minigame features and BoxOfBits has all the essentials/tools features?

**Comment by dragonwocky** [comment]
Also, can someone please test InstaPerms? I updated it but I dunno if it works because I haven't managed to get a test server running properly yet.

**Comment by remotevase** [comment]
I can't test. But I will start BoxCore.

**Comment by dragonwocky** [comment]
Ok.
