### ISSUE TITLE
General Chat

### ISSUE THREAD

**Issue by remotevase** [BoxOfDevs/Archived#2]
Regular chatroom

**Comment by Vaults1** [comment]
What should I chat about?

btw, there is a hidden message in this comment.

**Comment by dragonwocky** [comment]
Well.... Is that hidden message the words "hidden message"?

**Comment by remotevase** [comment]
Probably XP

**Comment by remotevase** [comment]
Main chat on twitter, but this is ffor otherstuff too

**Comment by Vaults1** [comment]
No. Nice try. ;)
